version: '3.7'

services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - yolofund

  db:
    image: postgres
    networks:
      - yolofund
    env_file: 
      - .env
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    
  adminer:
    image: adminer
    networks:
      - yolofund
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.http.routers.adminer.rule=Host(`adminer.localhost`)"
      - "traefik.http.routers.adminer.entrypoints=web"

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - yolofund
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.gateway.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.gateway.rule=Host(`api.localhost`)"
      - "traefik.http.routers.gateway.entrypoints=web"

networks:
  yolofund:
    driver: bridge